=== zehrahshameer07/cordelias_cafe/patisserie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.cordeliascafe.com" xmlns="http://www.cordeliascafe.com" elementFormDefault="qualified">
    <xs:element name="patisserie">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cakes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cake" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="price" type="xs:decimal"/>
                                        <xs:element name="weight">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="unit" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="isAvailable" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== zehrahshameer07/cordelias_cafe/patisserie.xml
<?xml version="1.0" encoding="UTF-8"?>
<patisserie xmlns="http://www.cordeliascafe.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cordeliascafe.com patisserie.xsd">
    <cakes>
        <cake>
            <name>Classic Vanilla</name>
            <price>999</price>
            <weight unit="kg">1.5</weight>
            <isAvailable>true</isAvailable>
        </cake>
        <cake>
            <name>Chocolate Truffle</name>
            <price>2550</price>
            <weight unit="kg">2.0</weight>
            <isAvailable>false</isAvailable>
        </cake>
    </cakes>
</patisserie>
